name: Vavoo Signature Updater
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Repoya yazma izni verir
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: pip install requests

      - name: Verileri Güncelle ve Kaydet
        run: |
          python updater.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Dosyaları ekle (hata vermemesi için || true ekledik)
          git add signature.txt playlist.m3u || true
          # Eğer değişiklik varsa commit et ve pushla
          if git diff --staged --quiet; then
            echo "Değişiklik yok, işlem atlanıyor."
          else
            git commit -m "Playlist ve İmza Güncellendi: $(date)"
            git push
          fi
